name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build
        with:
          working-directory: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          working-directory: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
